// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PsvManager.Infrastructure.Data.Contexts;

#nullable disable

namespace PsvManager.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PsvContext))]
    [Migration("20240222222315_updateData")]
    partial class updateData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PsvManager.Infrastructure.Data.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TownOrCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e44a463-3b65-4b2c-81eb-52bc0e2b51c5"),
                            HouseNumber = "123",
                            Postcode = "12345",
                            StreetName = "Main St",
                            TownOrCity = "New York"
                        },
                        new
                        {
                            Id = new Guid("34740eca-cd06-4c20-a354-fc870d447ace"),
                            HouseNumber = "456",
                            Postcode = "67890",
                            StreetName = "Elm St",
                            TownOrCity = "Los Angeles"
                        });
                });

            modelBuilder.Entity("PsvManager.Infrastructure.Data.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Forename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7e666b4-7c36-4b11-91d7-67ccf41e182f"),
                            AddressId = new Guid("0e44a463-3b65-4b2c-81eb-52bc0e2b51c5"),
                            Forename = "John",
                            LicenseNumber = "Test1234",
                            Surname = "Bon Jovi"
                        },
                        new
                        {
                            Id = new Guid("8d9f847c-a995-471d-8fc1-f67531abce97"),
                            AddressId = new Guid("34740eca-cd06-4c20-a354-fc870d447ace"),
                            Forename = "Craig",
                            LicenseNumber = "Test4567",
                            Surname = "Cheney"
                        });
                });

            modelBuilder.Entity("PsvManager.Infrastructure.Data.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxPassengers")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ec409082-19da-43c7-8570-92ce7f68e513"),
                            Make = "Toyota",
                            MaxPassengers = 5,
                            Model = "Camry",
                            Registration = "ABC123"
                        },
                        new
                        {
                            Id = new Guid("3fa9b0c4-ac4b-431e-8684-64c878af9d29"),
                            Make = "Honda",
                            MaxPassengers = 4,
                            Model = "Accord",
                            Registration = "DEF456"
                        });
                });

            modelBuilder.Entity("PsvManager.Infrastructure.Data.Entities.Driver", b =>
                {
                    b.HasOne("PsvManager.Infrastructure.Data.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
